import { ITreeNode } from "../components/tree/common/types";
import { FAKE_CURRENT_USER_ID } from "./constants";

export const mockData: ITreeNode[] = [
  {
    id: 1,
    parentId: null,
    name: "Корневая бригада",
    type: "brigade",
    ordersQuantity: 6,
    ordersTotalSum: 50000,
    workload: 45,

    children: [
      {
        id: 2,
        parentId: 1,
        name: "Бригада 1",
        type: "brigade",
        ordersQuantity: 3,
        ordersTotalSum: 30000,
        workload: 30,

        children: [
          {
            id: 6,
            parentId: 2,
            name: "Бригада тест",
            type: "brigade",
            ordersQuantity: 3,
            ordersTotalSum: 30000,
            workload: 30,
            children: [
              {
                id: 9,
                parentId: 6,
                name: "Бригадир",
                type: "workplace",
                worker: {
                  id: 10,
                  name: "Артур",
                  surname: "Слепаков",
                  patronymic: "Александрович",
                  position: "Бригадир",
                  image: "no_image_worker.svg",
                  isBrigadier: true,
                  orders: [
                    {
                      id: 8,
                      total_sum: 25000,
                      percent_of_work: 30,
                      order_status: "in_progress",
                      finish_planned_at: new Date("2024-01-15"),
                      finished_at: new Date("2024-01-14"),
                      start_planned_at: new Date("2024-01-05"),
                      started_at: new Date("2024-01-06"),
                      created_at: new Date("2024-01-03"),
                    },
                    {
                      id: 9,
                      total_sum: 11000,
                      percent_of_work: 100,
                      order_status: "completed",
                      finish_planned_at: new Date("2024-01-20"),
                      finished_at: new Date("2024-01-19"),
                      start_planned_at: new Date("2024-01-10"),
                      started_at: new Date("2024-01-11"),
                      created_at: new Date("2024-01-08"),
                    },
                    {
                      id: 10,
                      total_sum: 30000,
                      percent_of_work: 100,
                      order_status: "completed",
                      finish_planned_at: new Date("2024-01-25"),
                      finished_at: new Date("2024-01-24"),
                      start_planned_at: new Date("2024-01-15"),
                      started_at: new Date("2024-01-16"),
                      created_at: new Date("2024-01-13"),
                    },
                  ],
                },
              },
            ],
          },
          {
            id: 7,
            parentId: 2,
            name: "Маляр",
            type: "workplace",
            worker: {
              id: 5,
              name: "Семен",
              surname: "Слепаков",
              patronymic: "Александрович",
              position: "Маляр",
              image: "no_image_customer.svg",
              orders: [
                {
                  id: 1,
                  total_sum: 10000,
                  percent_of_work: 15,
                  order_status: "in_progress",
                  finish_planned_at: new Date("2024-12-10"),
                  finished_at: new Date("2024-12-09"),
                  start_planned_at: new Date("2024-12-01"),
                  started_at: new Date("2024-12-01"),
                  created_at: new Date("2024-11-30"),
                },
                {
                  id: 2,
                  total_sum: 20000,
                  percent_of_work: 100,
                  order_status: "completed",
                  finish_planned_at: new Date("2024-12-15"),
                  finished_at: new Date("2024-12-14"),
                  start_planned_at: new Date("2024-12-05"),
                  started_at: new Date("2024-12-05"),
                  created_at: new Date("2024-12-03"),
                },
                {
                  id: 3,
                  total_sum: 15000,
                  percent_of_work: 18,
                  order_status: "pending",
                  finish_planned_at: new Date("2024-12-20"),
                  finished_at: new Date("2024-12-19"),
                  start_planned_at: new Date("2024-12-10"),
                  started_at: new Date("2024-12-11"),
                  created_at: new Date("2024-12-09"),
                },
              ],
            },
          },
          {
            id: 17,
            parentId: 2,
            name: "Бригадир",
            type: "workplace",
            worker: {
              id: 5,
              name: "Николай",
              surname: "Слепаков",
              patronymic: "Александрович",
              position: "Бригадир",
              image: "no_image_worker.svg",
              isBrigadier: true,
              orders: [
                {
                  id: 11,
                  total_sum: 7000,
                  percent_of_work: 5,
                  order_status: "pending",
                  finish_planned_at: new Date("2024-01-30"),
                  finished_at: new Date("2024-01-29"),
                  start_planned_at: new Date("2024-01-20"),
                  started_at: new Date("2024-01-21"),
                  created_at: new Date("2024-01-18"),
                },
                {
                  id: 12,
                  total_sum: 17000,
                  percent_of_work: 22,
                  order_status: "in_progress",
                  finish_planned_at: new Date("2024-02-05"),
                  finished_at: new Date("2024-02-04"),
                  start_planned_at: new Date("2024-01-25"),
                  started_at: new Date("2024-01-26"),
                  created_at: new Date("2024-01-23"),
                },
                {
                  id: 13,
                  total_sum: 13000,
                  percent_of_work: 100,
                  order_status: "completed",
                  finish_planned_at: new Date("2024-02-10"),
                  finished_at: new Date("2024-02-09"),
                  start_planned_at: new Date("2024-02-01"),
                  started_at: new Date("2024-02-02"),
                  created_at: new Date("2024-01-30"),
                },
              ],
            },
          },
        ],
      },
      {
        id: 3,
        parentId: 1,
        name: "Бригада 2",
        type: "brigade",
        ordersQuantity: 6,
        ordersTotalSum: 300500,
        workload: 70,
        children: [
          {
            id: 15,
            parentId: 3,
            name: "Бригадир",
            type: "workplace",
            worker: {
              id: 16,
              name: "Вячеслав",
              surname: "Слепаков",
              patronymic: "Александрович",
              position: "Бригадир",
              image: "no_image_worker.svg",
              isBrigadier: true,
              orders: [
                {
                  id: 14,
                  total_sum: 6000,
                  percent_of_work: 100,
                  order_status: "completed",
                  finish_planned_at: new Date("2024-02-15"),
                  finished_at: new Date("2024-02-14"),
                  start_planned_at: new Date("2024-02-05"),
                  started_at: new Date("2024-02-06"),
                  created_at: new Date("2024-02-03"),
                },
                {
                  id: 15,
                  total_sum: 24000,
                  percent_of_work: 28,
                  order_status: "pending",
                  finish_planned_at: new Date("2024-02-20"),
                  finished_at: new Date("2024-02-19"),
                  start_planned_at: new Date("2024-02-10"),
                  started_at: new Date("2024-02-11"),
                  created_at: new Date("2024-02-08"),
                },
                {
                  id: 16,
                  total_sum: 19000,
                  percent_of_work: 24,
                  order_status: "in_progress",
                  finish_planned_at: new Date("2024-02-25"),
                  finished_at: new Date("2024-02-24"),
                  start_planned_at: new Date("2024-02-15"),
                  started_at: new Date("2024-02-16"),
                  created_at: new Date("2024-02-13"),
                },
              ],
            },
          },
        ],
      },
      {
        id: 4,
        parentId: 1,
        name: "Шиномонтажник",
        type: "workplace",
        worker: {
          id: 5,
          name: "Александр",
          surname: "Кузнецов",
          patronymic: "Александрович",
          position: "Механик",
          image: "no_image_customer.svg",
          orders: [
            {
              id: 4,
              total_sum: 12000,
              percent_of_work: 100,
              order_status: "completed",
              finish_planned_at: new Date("2024-12-25"),
              finished_at: new Date("2024-12-17"),
              start_planned_at: new Date("2024-12-15"),
              started_at: new Date("2024-12-16"),
              created_at: new Date("2024-12-13"),
            },
            {
              id: 5,
              total_sum: 18000,
              percent_of_work: 25,
              order_status: "in_progress",
              finish_planned_at: new Date("2024-12-30"),
              finished_at: new Date("2024-12-29"),
              start_planned_at: new Date("2024-12-20"),
              started_at: new Date("2024-12-21"),
              created_at: new Date("2024-12-18"),
            },
            {
              id: 6,
              total_sum: 14000,
              percent_of_work: 100,
              order_status: "completed",
              finish_planned_at: new Date("2024-01-05"),
              finished_at: new Date("2024-12-30"),
              start_planned_at: new Date("2024-12-25"),
              started_at: new Date("2024-12-26"),
              created_at: new Date("2024-12-23"),
            },
            {
              id: 7,
              total_sum: 9000,
              percent_of_work: 8,
              order_status: "pending",
              finish_planned_at: new Date("2024-01-10"),
              finished_at: new Date("2024-01-15"),
              start_planned_at: new Date("2024-01-01"),
              started_at: new Date("2024-01-13"),
              created_at: new Date("2024-12-31"),
            },
          ],
        },
      },
      {
        id: 8,
        parentId: 1,
        name: "Бригадир",
        type: "workplace",
        worker: {
          id: 5,
          name: "Михаил",
          surname: "Кузнецов",
          patronymic: "Александрович",
          position: "Бригадир",
          image: "no_image_worker.svg",
          isBrigadier: true,
          orders: [
            {
              id: 17,
              total_sum: 8000,
              percent_of_work: 100,
              order_status: "completed",
              finish_planned_at: new Date("2024-03-01"),
              finished_at: new Date("2024-02-28"),
              start_planned_at: new Date("2024-02-20"),
              started_at: new Date("2024-02-21"),
              created_at: new Date("2024-02-18"),
            },
            {
              id: 18,
              total_sum: 21000,
              percent_of_work: 26,
              order_status: "in_progress",
              finish_planned_at: new Date("2024-03-05"),
              finished_at: new Date("2024-03-04"),
              start_planned_at: new Date("2024-02-25"),
              started_at: new Date("2024-02-26"),
              created_at: new Date("2024-02-23"),
            },
          ],
        },
      },
    ],
  },
];

export const personalMockData: ITreeNode = {
  id: FAKE_CURRENT_USER_ID,
  parentId: null,
  name: "Личный",
  type: "workplace",
  worker: {
    id: 5,
    name: "Семен",
    surname: "Слепаков",
    patronymic: "Александрович",
    position: "Маляр",
    image: "no_image_customer.svg",
    orders: [
      {
        id: 1,
        total_sum: 10000,
        percent_of_work: 15,
        order_status: "in_progress",
        finish_planned_at: new Date("2024-12-10"),
        finished_at: new Date("2024-12-09"),
        start_planned_at: new Date("2024-12-01"),
        started_at: new Date("2024-12-01"),
        created_at: new Date("2024-11-30"),
      },
      {
        id: 2,
        total_sum: 20000,
        percent_of_work: 100,
        order_status: "completed",
        finish_planned_at: new Date("2024-12-15"),
        finished_at: new Date("2024-12-14"),
        start_planned_at: new Date("2024-12-05"),
        started_at: new Date("2024-12-05"),
        created_at: new Date("2024-12-03"),
      },
      {
        id: 3,
        total_sum: 15000,
        percent_of_work: 18,
        order_status: "pending",
        finish_planned_at: new Date("2024-12-20"),
        finished_at: new Date("2024-12-19"),
        start_planned_at: new Date("2024-12-10"),
        started_at: new Date("2024-12-11"),
        created_at: new Date("2024-12-09"),
      },
    ],
  },
};
