import { ITreeNode } from "../../tree/common/types";

export const mockData: ITreeNode[] = [
  {
    id: 1,
    parentId: null,
    name: "Корневая бригада",
    type: "brigade",
    ordersQuantity: 6,
    ordersTotalSum: 50000,
    workload: 45,
    brigadier: {
      id: 1,
      name: "Саша",
      surname: "Белый",
      patronymic: "Иванович",
      position: "Директор",
      image: "no_image_worker.svg",
    },
    children: [
      {
        id: 2,
        parentId: 1,
        name: "Бригада 1",
        type: "brigade",
        ordersQuantity: 3,
        ordersTotalSum: 30000,
        workload: 30,
        brigadier: {
          id: 2,
          name: "Виктор",
          surname: "Пчела",
          patronymic: "Алексеевич",
          position: "Менеджер",
          image: "no_image_worker.svg",
        },
        children: [
          {
            id: 6,
            parentId: 2,
            name: "Бригада тест",
            type: "brigade",
            ordersQuantity: 3,
            ordersTotalSum: 30000,
            workload: 30,
            brigadier: {
              id: 2,
              name: "Евгений",
              surname: "Онегин",
              patronymic: "Алексеевич",
              position: "Менеджер",
              image: "no_image_worker.svg",
            },
          },
          {
            id: 7,
            parentId: 2,
            name: "Маляр",
            type: "workplace",
            worker: {
              id: 5,
              name: "Семен",
              surname: "Слепаков",
              patronymic: "Александрович",
              position: "Маляр",
              image: "no_image_customer.svg",
            },
          },
        ],
      },
      {
        id: 3,
        parentId: 1,
        name: "Бригада 2",
        type: "brigade",
        ordersQuantity: 6,
        ordersTotalSum: 300500,
        workload: 70,
        brigadier: {
          id: 3,
          name: "Космос",
          surname: "Холмогоров",
          patronymic: "Евгеньевич",
          position: "Старший механик",
          image: "no_image_worker.svg",
        },
      },
      {
        id: 4,
        parentId: 1,
        name: "Шиномонтажник",
        type: "workplace",
        worker: {
          id: 5,
          name: "Александр",
          surname: "Кузнецов",
          patronymic: "Александрович",
          position: "Механик",
          image: "no_image_customer.svg",
        },
      },
    ],
  },
];
